//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GlobalUser
    {
        public GlobalUser()
        {
            this.ExceptionsUsers = new HashSet<ExceptionsUser>();
            this.Markets = new HashSet<Market>();
            this.People = new HashSet<Person>();
            this.Places = new HashSet<Place>();
            this.UserProfiles = new HashSet<UserProfile>();
            this.OrganizationUsersMaps = new HashSet<OrganizationUsersMap>();
            this.ShiftsUsers = new HashSet<ShiftsUser>();
            this.UserSubscriptions = new HashSet<UserSubscription>();
            this.WorkDaysUsers = new HashSet<WorkDaysUser>();
        }
    
        public System.Guid UserGUID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Role_Id { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ReportingPlaceType { get; set; }
        public Nullable<System.Guid> ReportPlaceGUID { get; set; }
        public bool IsExempt { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public string USERID { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual ICollection<ExceptionsUser> ExceptionsUsers { get; set; }
        public virtual ICollection<Market> Markets { get; set; }
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Place> Places { get; set; }
        public virtual ICollection<UserProfile> UserProfiles { get; set; }
        public virtual ICollection<OrganizationUsersMap> OrganizationUsersMaps { get; set; }
        public virtual ICollection<ShiftsUser> ShiftsUsers { get; set; }
        public virtual ICollection<UserSubscription> UserSubscriptions { get; set; }
        public virtual ICollection<WorkDaysUser> WorkDaysUsers { get; set; }
    }
}
