//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobFormData
    {
        public System.Guid JobFormDataGUID { get; set; }
        public Nullable<System.Guid> JobFormGUID { get; set; }
        public Nullable<System.Guid> JobGUID { get; set; }
        public string ControlsID { get; set; }
        public string Val { get; set; }
        public string ValID { get; set; }
    }
}
