//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobForum
    {
        public System.Guid JobForumGUID { get; set; }
        public Nullable<System.Guid> JobOfferGUID { get; set; }
        public Nullable<System.Guid> JobGUID { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public Nullable<System.Guid> ParentJobForumGUID { get; set; }
        public string ForumText { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<short> ForumStatus { get; set; }
        public Nullable<System.DateTime> StartTimePreference { get; set; }
        public Nullable<double> CounterCostOffer { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
