//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobForumStatu
    {
        public System.Guid ForumStatusGUID { get; set; }
        public Nullable<System.Guid> OrganizationGUID { get; set; }
        public short ForumStatus { get; set; }
        public string StatusText { get; set; }
    }
}
