//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobForm
    {
        public System.Guid JobFormGUID { get; set; }
        public Nullable<System.Guid> OrganizationGUID { get; set; }
        public string Skill { get; set; }
        public Nullable<short> JobClass { get; set; }
        public Nullable<short> LocationType { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FriendlyName { get; set; }
        public string JobForm1 { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    }
}
