//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobOffer
    {
        public System.Guid JobOfferGUID { get; set; }
        public Nullable<System.Guid> JobGUID { get; set; }
        public Nullable<System.Guid> ManagerUserGUID { get; set; }
        public string OfferText { get; set; }
        public string OfferValue { get; set; }
        public Nullable<System.DateTime> ExpiryDateTime { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
