//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Market
    {
        public System.Guid MarketGUID { get; set; }
        public Nullable<System.Guid> OrganizationGUID { get; set; }
        public string MarketID { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public Nullable<int> EntityType { get; set; }
        public Nullable<System.Guid> OwnerGUID { get; set; }
        public string MarketName { get; set; }
        public Nullable<System.Guid> RegionGUID { get; set; }
        public Nullable<System.Guid> TerritoryGUID { get; set; }
        public Nullable<System.Guid> PrimaryContactGUID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobilePhone { get; set; }
        public string MarketPhone { get; set; }
        public string HomePhone { get; set; }
        public string Emails { get; set; }
        public string TimeZone { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string ImageURL { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ParentID { get; set; }
        public string TeritoryID { get; set; }
        public string RegionName { get; set; }
        public string RMUserID { get; set; }
        public string FMUserID { get; set; }
        public string StoreJSON { get; set; }
        public Nullable<System.DateTime> LastStoreVisitedDate { get; set; }
    
        public virtual GlobalUser GlobalUser { get; set; }
        public virtual Region Region { get; set; }
        public virtual Territory Territory { get; set; }
    }
}
