//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterLogin
    {
        public System.Guid LoginGUID { get; set; }
        public Nullable<short> LoginType { get; set; }
        public System.Guid UserGUID { get; set; }
        public bool IsActive { get; set; }
        public string SessionID { get; set; }
        public System.DateTime ExpiryTime { get; set; }
        public Nullable<int> SessionTimeOut { get; set; }
        public Nullable<bool> IsLoggedIn { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    }
}
