//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationSubscription
    {
        public System.Guid OrganizationSubscriptionGUID { get; set; }
        public System.Guid OrganizationGUID { get; set; }
        public int Version { get; set; }
        public bool IsActive { get; set; }
        public int SubscriptionPurchased { get; set; }
        public int SubscriptionConsumed { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Organization Organization { get; set; }
    }
}
