//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationUsersMap
    {
        public System.Guid OrganizationUserMapGUID { get; set; }
        public System.Guid OrganizationGUID { get; set; }
        public System.Guid UserGUID { get; set; }
        public bool IsContractor { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public short Status { get; set; }
        public Nullable<double> HourlyRate { get; set; }
        public Nullable<System.Guid> RegionGUID { get; set; }
        public Nullable<System.Guid> TerritoryGUID { get; set; }
        public string UserType { get; set; }
        public string UserSubTypeCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    
        public virtual GlobalUser GlobalUser { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
