//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class POs
    {
        public System.Guid POGUID { get; set; }
        public Nullable<System.Guid> OrganizationGUID { get; set; }
        public Nullable<System.Guid> RegionGUID { get; set; }
        public Nullable<System.Guid> TerritoryGUID { get; set; }
        public string PONumber { get; set; }
        public Nullable<short> Status { get; set; }
        public string Description { get; set; }
        public string PlaceID { get; set; }
        public Nullable<short> LocationType { get; set; }
        public string MarketID { get; set; }
        public string EndCustomerAddress { get; set; }
        public string EndCustomerName { get; set; }
        public string EndCustomerPhone { get; set; }
        public string WorkerName { get; set; }
        public Nullable<bool> CustomBooleanValue { get; set; }
        public Nullable<short> JobClass { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> PreferredDateTime { get; set; }
        public Nullable<double> EstimatedCost { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.Guid> CreateBy { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
        public string POID { get; set; }
        public string TerritoryID { get; set; }
        public string RegionName { get; set; }
        public string RMUserID { get; set; }
        public string FMUserID { get; set; }
        public string POJobType { get; set; }
        public string POJobCode { get; set; }
        public string POJson { get; set; }
        public string InstallerName { get; set; }
        public string POCustomerName { get; set; }
        public string POCustomerPhone { get; set; }
        public string POCustomerMobile { get; set; }
    }
}
