//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillsOrganization
    {
        public SkillsOrganization()
        {
            this.SkillsUsers = new HashSet<SkillsUser>();
        }
    
        public System.Guid OrganizationSkillGuid { get; set; }
        public Nullable<System.Guid> OrganizationGUID { get; set; }
        public string Skill { get; set; }
        public string SkillLevel { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<SkillsUser> SkillsUsers { get; set; }
    }
}
