//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Territory
    {
        public Territory()
        {
            this.Markets = new HashSet<Market>();
        }
    
        public System.Guid TerritoryGUID { get; set; }
        public Nullable<System.Guid> RegionGUID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> OrganizationGUID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string Description { get; set; }
        public string TerritoryID { get; set; }
    
        public virtual ICollection<Market> Markets { get; set; }
        public virtual Region Region { get; set; }
    }
}
