//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubscription
    {
        public System.Guid UserSubscriptionGUID { get; set; }
        public System.Guid UserGUID { get; set; }
        public Nullable<System.Guid> OrganizationSubscriptionGUID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual GlobalUser GlobalUser { get; set; }
    }
}
