//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDaysUser
    {
        public System.Guid UserWorkdaysGUID { get; set; }
        public Nullable<System.Guid> OrganizationWorkDaysGUID { get; set; }
        public Nullable<System.Guid> UserGUID { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    
        public virtual GlobalUser GlobalUser { get; set; }
        public virtual WorkDaysOrganization WorkDaysOrganization { get; set; }
    }
}
