//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Linq;

    public partial class WorkersInMotionDB : DbContext
    {
        //public WorkersInMotionDB()
        //    : base("name=WorkersInMotionDB")
        //{
        //}
        public WorkersInMotionDB()
            : base(GetConnectionString())
        {
        }
        public static string GetConnectionString()
        {
            string value = Environment.GetEnvironmentVariable("DBAPPDATA");
            // If necessary, create it. 
            if (value == null)
            {
                //Environment.SetEnvironmentVariable("AzureAPPDATA", "hvknao7jdf.database.windows.net,1433;initial catalog=WIM;user id=staywellsa;password=wim12345*");
                Environment.SetEnvironmentVariable("DBAPPDATA", "209.198.193.74;initial catalog=WIM31;persist security info=True;user id=admin;password=Admin1234");
                //Environment.SetEnvironmentVariable("DBAPPDATA", "PRABHU\\MSSQL;initial catalog=WIM31;persist security info=True;user id=sa;password=sa");
            }
            //AppDomain.CurrentDomain.SetData("DataDirectory", Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData));
            var conStr = System.Configuration.ConfigurationManager.ConnectionStrings["WorkersInMotionDB"].ConnectionString;
            conStr = conStr.Replace("|DataDirectory|",
                Environment.GetEnvironmentVariable("DBAPPDATA"));
            return conStr;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<AspNetRole> AspNetRoles { get; set; }
        public DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public DbSet<AspNetUser> AspNetUsers { get; set; }
        public DbSet<ExceptionsOrganization> ExceptionsOrganizations { get; set; }
        public DbSet<ExceptionsUser> ExceptionsUsers { get; set; }
        public DbSet<GlobalUser> GlobalUsers { get; set; }
        public DbSet<JobAssigned> JobAssigneds { get; set; }
        public DbSet<JobCostType> JobCostTypes { get; set; }
        public DbSet<JobForum> JobForums { get; set; }
        public DbSet<JobNote> JobNotes { get; set; }
        public DbSet<JobOffer> JobOffers { get; set; }
        public DbSet<JobProgress> JobProgresses { get; set; }
        public DbSet<Job> Jobs { get; set; }
        public DbSet<Market> Markets { get; set; }
        public DbSet<MasterLogin> MasterLogins { get; set; }
        public DbSet<Organization> Organizations { get; set; }
        public DbSet<OrganizationSubscription> OrganizationSubscriptions { get; set; }
        public DbSet<OrganizationUsersMap> OrganizationUsersMaps { get; set; }
        public DbSet<Person> People { get; set; }
        public DbSet<Place> Places { get; set; }
        public DbSet<POs> POs { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<ShiftsOrganization> ShiftsOrganizations { get; set; }
        public DbSet<ShiftsUser> ShiftsUsers { get; set; }
        public DbSet<SkillsOrganization> SkillsOrganizations { get; set; }
        public DbSet<SkillsUser> SkillsUsers { get; set; }
        public DbSet<Territory> Territories { get; set; }
        public DbSet<UserDevice> UserDevices { get; set; }
        public DbSet<UserHeartBeat> UserHeartBeats { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UserSubscription> UserSubscriptions { get; set; }
        public DbSet<WorkDaysOrganization> WorkDaysOrganizations { get; set; }
        public DbSet<WorkDaysUser> WorkDaysUsers { get; set; }
        public DbSet<JobFormData> JobFormDatas { get; set; }
        public DbSet<JobForm> JobForms { get; set; }
        public DbSet<JobForumStatu> JobForumStatus { get; set; }
        public DbSet<JobStatu> JobStatus { get; set; }
        public DbSet<JobStatusOrganization> JobStatusOrganizations { get; set; }
        public DbSet<JobSubStatu> JobSubStatus { get; set; }
        public DbSet<JobSubStatusOrganization> JobSubStatusOrganizations { get; set; }
        public DbSet<OptionList> OptionLists { get; set; }

        [System.Data.Entity.DbFunction("WorkersInMotionDB", "SplitString")]
        public virtual IQueryable<SplitString_Result> SplitString(string pStringToSplit)
        {
            var pStringToSplitParameter = pStringToSplit != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pStringToSplit", pStringToSplit) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pStringToSplit", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<SplitString_Result>("[WorkersInMotionDB].[SplitString](@pStringToSplit)", pStringToSplitParameter);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<p_GetJobs_Result> p_GetJobs(Nullable<System.Guid> pUserGUID, Nullable<int> pStatusCode, System.Data.Entity.Core.Objects.ObjectParameter pErrorCode)
        {
            var pUserGUIDParameter = pUserGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserGUID", pUserGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserGUID", typeof(System.Guid));

            var pStatusCodeParameter = pStatusCode.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pStatusCode", pStatusCode) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pStatusCode", typeof(int));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetJobs_Result>("p_GetJobs", pUserGUIDParameter, pStatusCodeParameter, pErrorCode);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<p_GetJobStatistics_Result> p_GetJobStatistics(Nullable<System.Guid> pUserGUID, Nullable<bool> pStatsForManager, string pUserType, Nullable<System.Guid> pRegionGUID, Nullable<System.Guid> pTerritoryGUID, Nullable<System.DateTime> pDate, System.Data.Entity.Core.Objects.ObjectParameter pErrorCode)
        {
            var pUserGUIDParameter = pUserGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserGUID", pUserGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserGUID", typeof(System.Guid));

            var pStatsForManagerParameter = pStatsForManager.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pStatsForManager", pStatsForManager) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pStatsForManager", typeof(bool));

            var pUserTypeParameter = pUserType != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserType", pUserType) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserType", typeof(string));

            var pRegionGUIDParameter = pRegionGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pRegionGUID", pRegionGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pRegionGUID", typeof(System.Guid));

            var pTerritoryGUIDParameter = pTerritoryGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pTerritoryGUID", pTerritoryGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pTerritoryGUID", typeof(System.Guid));

            var pDateParameter = pDate.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pDate", pDate) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pDate", typeof(System.DateTime));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetJobStatistics_Result>("p_GetJobStatistics", pUserGUIDParameter, pStatsForManagerParameter, pUserTypeParameter, pRegionGUIDParameter, pTerritoryGUIDParameter, pDateParameter, pErrorCode);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<p_GetOpenJobs_Result> p_GetOpenJobs(Nullable<System.Guid> pUserGUID, Nullable<System.Guid> pOrganizationGUID, Nullable<System.Guid> pRegionGUID, Nullable<System.Guid> pTerritoryGUID, string pUserType, string pStatusCode, System.Data.Entity.Core.Objects.ObjectParameter pErrorCode)
        {
            var pUserGUIDParameter = pUserGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserGUID", pUserGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserGUID", typeof(System.Guid));

            var pOrganizationGUIDParameter = pOrganizationGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pOrganizationGUID", pOrganizationGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pOrganizationGUID", typeof(System.Guid));

            var pRegionGUIDParameter = pRegionGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pRegionGUID", pRegionGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pRegionGUID", typeof(System.Guid));

            var pTerritoryGUIDParameter = pTerritoryGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pTerritoryGUID", pTerritoryGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pTerritoryGUID", typeof(System.Guid));

            var pUserTypeParameter = pUserType != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserType", pUserType) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserType", typeof(string));

            var pStatusCodeParameter = pStatusCode != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pStatusCode", pStatusCode) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pStatusCode", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetOpenJobs_Result>("p_GetOpenJobs", pUserGUIDParameter, pOrganizationGUIDParameter, pRegionGUIDParameter, pTerritoryGUIDParameter, pUserTypeParameter, pStatusCodeParameter, pErrorCode);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<p_GetOrganizationsForSkills_Result> p_GetOrganizationsForSkills(string pSkills, System.Data.Entity.Core.Objects.ObjectParameter pErrorCode)
        {
            var pSkillsParameter = pSkills != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pSkills", pSkills) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pSkills", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetOrganizationsForSkills_Result>("p_GetOrganizationsForSkills", pSkillsParameter, pErrorCode);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<p_GetUsers_Result> p_GetUsers(string pSessionID, Nullable<System.Guid> pUserGUID, System.Data.Entity.Core.Objects.ObjectParameter pErrorCode)
        {
            var pSessionIDParameter = pSessionID != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pSessionID", pSessionID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pSessionID", typeof(string));

            var pUserGUIDParameter = pUserGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserGUID", pUserGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserGUID", typeof(System.Guid));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetUsers_Result>("p_GetUsers", pSessionIDParameter, pUserGUIDParameter, pErrorCode);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<p_GetUsersAvailability_Result> p_GetUsersAvailability(string pSkill, Nullable<System.DateTime> pDate, Nullable<System.TimeSpan> pStartTime, Nullable<System.TimeSpan> pEndTime, Nullable<double> pDuration, Nullable<System.Guid> pOrganizationGUID, Nullable<System.Guid> pRegionGUID, Nullable<System.Guid> pTerritoryGUID, Nullable<double> pLatitude, Nullable<double> pLongitude, Nullable<bool> pSearchWithinZoneArea, Nullable<short> pSearch, System.Data.Entity.Core.Objects.ObjectParameter pErrorCode)
        {
            var pSkillParameter = pSkill != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pSkill", pSkill) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pSkill", typeof(string));

            var pDateParameter = pDate.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pDate", pDate) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pDate", typeof(System.DateTime));

            var pStartTimeParameter = pStartTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pStartTime", pStartTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pStartTime", typeof(System.TimeSpan));

            var pEndTimeParameter = pEndTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pEndTime", pEndTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pEndTime", typeof(System.TimeSpan));

            var pDurationParameter = pDuration.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pDuration", pDuration) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pDuration", typeof(double));

            var pOrganizationGUIDParameter = pOrganizationGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pOrganizationGUID", pOrganizationGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pOrganizationGUID", typeof(System.Guid));

            var pRegionGUIDParameter = pRegionGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pRegionGUID", pRegionGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pRegionGUID", typeof(System.Guid));

            var pTerritoryGUIDParameter = pTerritoryGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pTerritoryGUID", pTerritoryGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pTerritoryGUID", typeof(System.Guid));

            var pLatitudeParameter = pLatitude.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLatitude", pLatitude) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLatitude", typeof(double));

            var pLongitudeParameter = pLongitude.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLongitude", pLongitude) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLongitude", typeof(double));

            var pSearchWithinZoneAreaParameter = pSearchWithinZoneArea.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pSearchWithinZoneArea", pSearchWithinZoneArea) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pSearchWithinZoneArea", typeof(bool));

            var pSearchParameter = pSearch.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pSearch", pSearch) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pSearch", typeof(short));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetUsersAvailability_Result>("p_GetUsersAvailability", pSkillParameter, pDateParameter, pStartTimeParameter, pEndTimeParameter, pDurationParameter, pOrganizationGUIDParameter, pRegionGUIDParameter, pTerritoryGUIDParameter, pLatitudeParameter, pLongitudeParameter, pSearchWithinZoneAreaParameter, pSearchParameter, pErrorCode);
        }

        public virtual System.Data.Entity.Core.Objects.ObjectResult<p_GetUsersLocationForADate_Result> p_GetUsersLocationForADate(Nullable<System.Guid> pOrganizationGUID, Nullable<System.DateTime> pDate, Nullable<System.TimeSpan> pStartTime, Nullable<System.TimeSpan> pEndTime, Nullable<double> pDuration, Nullable<System.Guid> pRegionGUID, Nullable<System.Guid> pTerritoryGUID, Nullable<double> pLatitude, Nullable<double> pLongitude, Nullable<bool> pSearchWithinZoneArea, Nullable<short> pSearch, System.Data.Entity.Core.Objects.ObjectParameter pErrorCode)
        {
            var pOrganizationGUIDParameter = pOrganizationGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pOrganizationGUID", pOrganizationGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pOrganizationGUID", typeof(System.Guid));

            var pDateParameter = pDate.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pDate", pDate) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pDate", typeof(System.DateTime));

            var pStartTimeParameter = pStartTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pStartTime", pStartTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pStartTime", typeof(System.TimeSpan));

            var pEndTimeParameter = pEndTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pEndTime", pEndTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pEndTime", typeof(System.TimeSpan));

            var pDurationParameter = pDuration.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pDuration", pDuration) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pDuration", typeof(double));

            var pRegionGUIDParameter = pRegionGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pRegionGUID", pRegionGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pRegionGUID", typeof(System.Guid));

            var pTerritoryGUIDParameter = pTerritoryGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pTerritoryGUID", pTerritoryGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pTerritoryGUID", typeof(System.Guid));

            var pLatitudeParameter = pLatitude.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLatitude", pLatitude) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLatitude", typeof(double));

            var pLongitudeParameter = pLongitude.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLongitude", pLongitude) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLongitude", typeof(double));

            var pSearchWithinZoneAreaParameter = pSearchWithinZoneArea.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pSearchWithinZoneArea", pSearchWithinZoneArea) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pSearchWithinZoneArea", typeof(bool));

            var pSearchParameter = pSearch.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pSearch", pSearch) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pSearch", typeof(short));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetUsersLocationForADate_Result>("p_GetUsersLocationForADate", pOrganizationGUIDParameter, pDateParameter, pStartTimeParameter, pEndTimeParameter, pDurationParameter, pRegionGUIDParameter, pTerritoryGUIDParameter, pLatitudeParameter, pLongitudeParameter, pSearchWithinZoneAreaParameter, pSearchParameter, pErrorCode);
        }

        public virtual int p_Lognin(string pUserName, string pPassword, Nullable<short> pLoginType, string pDeviceID, string pIPAddress, string pDeviceInfo, Nullable<short> pDeviceType, string pPhone, string pTimeZone, System.Data.Entity.Core.Objects.ObjectParameter pErrorCode)
        {
            var pUserNameParameter = pUserName != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserName", pUserName) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pUserName", typeof(string));

            var pPasswordParameter = pPassword != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pPassword", pPassword) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pPassword", typeof(string));

            var pLoginTypeParameter = pLoginType.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLoginType", pLoginType) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLoginType", typeof(short));

            var pDeviceIDParameter = pDeviceID != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pDeviceID", pDeviceID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pDeviceID", typeof(string));

            var pIPAddressParameter = pIPAddress != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pIPAddress", pIPAddress) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pIPAddress", typeof(string));

            var pDeviceInfoParameter = pDeviceInfo != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pDeviceInfo", pDeviceInfo) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pDeviceInfo", typeof(string));

            var pDeviceTypeParameter = pDeviceType.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pDeviceType", pDeviceType) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pDeviceType", typeof(short));

            var pPhoneParameter = pPhone != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pPhone", pPhone) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pPhone", typeof(string));

            var pTimeZoneParameter = pTimeZone != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pTimeZone", pTimeZone) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pTimeZone", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Lognin", pUserNameParameter, pPasswordParameter, pLoginTypeParameter, pDeviceIDParameter, pIPAddressParameter, pDeviceInfoParameter, pDeviceTypeParameter, pPhoneParameter, pTimeZoneParameter, pErrorCode);
        }

        public virtual int p_UpdateJob(Nullable<System.Guid> pJobGUID, Nullable<int> pJobReferenceNo, Nullable<System.Guid> pOrganizationGUID, Nullable<System.Guid> pRegionGUID, Nullable<System.Guid> pTerritoryGUID, Nullable<short> pLocationType, Nullable<System.Guid> pCustomerGUID, Nullable<System.Guid> pCustomerStopGUID, Nullable<System.Guid> pServicePointGUID, string pServiceAddress, Nullable<double> pLatitude, Nullable<double> pLongitude, Nullable<System.Guid> pAssignedUserGUID, Nullable<System.Guid> pManagerUserGUID, Nullable<bool> pIsActive, Nullable<bool> pIsDeleted, Nullable<bool> pIsUrgent, Nullable<int> pStatusCode, Nullable<int> pSubStatusCode, Nullable<bool> pIsSecheduled, string pJobName, Nullable<System.DateTime> pPreferedStartTime, Nullable<System.DateTime> pPreferedEndTime, Nullable<System.DateTime> pScheduledStartTime, Nullable<System.DateTime> pScheduledEndTime, Nullable<System.DateTime> pActialStartTime, Nullable<System.DateTime> pActualEndTime, Nullable<double> pEstimatedDutation, Nullable<double> pQuotedDuration, Nullable<double> pActualDuration, Nullable<short> pCostType, Nullable<double> pQuotedCost, Nullable<double> pActualCost, string pJobForm, Nullable<System.Guid> pJobFormGUID, Nullable<short> pSignOffRequired, string pSignoffName, Nullable<short> pPictureRequired, string pPictureDescription, Nullable<bool> pLocationSpecific, Nullable<System.DateTime> pCreateDate, Nullable<System.Guid> pCreateBy, Nullable<System.DateTime> pLastModifiedDate, Nullable<System.Guid> pLastModifiedBy, System.Data.Entity.Core.Objects.ObjectParameter pErrorCode)
        {
            var pJobGUIDParameter = pJobGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobGUID", pJobGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobGUID", typeof(System.Guid));

            var pJobReferenceNoParameter = pJobReferenceNo.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobReferenceNo", pJobReferenceNo) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobReferenceNo", typeof(int));

            var pOrganizationGUIDParameter = pOrganizationGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pOrganizationGUID", pOrganizationGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pOrganizationGUID", typeof(System.Guid));

            var pRegionGUIDParameter = pRegionGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pRegionGUID", pRegionGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pRegionGUID", typeof(System.Guid));

            var pTerritoryGUIDParameter = pTerritoryGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pTerritoryGUID", pTerritoryGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pTerritoryGUID", typeof(System.Guid));

            var pLocationTypeParameter = pLocationType.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLocationType", pLocationType) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLocationType", typeof(short));

            var pCustomerGUIDParameter = pCustomerGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pCustomerGUID", pCustomerGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pCustomerGUID", typeof(System.Guid));

            var pCustomerStopGUIDParameter = pCustomerStopGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pCustomerStopGUID", pCustomerStopGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pCustomerStopGUID", typeof(System.Guid));

            var pServicePointGUIDParameter = pServicePointGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pServicePointGUID", pServicePointGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pServicePointGUID", typeof(System.Guid));

            var pServiceAddressParameter = pServiceAddress != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pServiceAddress", pServiceAddress) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pServiceAddress", typeof(string));

            var pLatitudeParameter = pLatitude.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLatitude", pLatitude) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLatitude", typeof(double));

            var pLongitudeParameter = pLongitude.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLongitude", pLongitude) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLongitude", typeof(double));

            var pAssignedUserGUIDParameter = pAssignedUserGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pAssignedUserGUID", pAssignedUserGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pAssignedUserGUID", typeof(System.Guid));

            var pManagerUserGUIDParameter = pManagerUserGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pManagerUserGUID", pManagerUserGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pManagerUserGUID", typeof(System.Guid));

            var pIsActiveParameter = pIsActive.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pIsActive", pIsActive) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pIsActive", typeof(bool));

            var pIsDeletedParameter = pIsDeleted.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pIsDeleted", pIsDeleted) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pIsDeleted", typeof(bool));

            var pIsUrgentParameter = pIsUrgent.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pIsUrgent", pIsUrgent) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pIsUrgent", typeof(bool));

            var pStatusCodeParameter = pStatusCode.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pStatusCode", pStatusCode) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pStatusCode", typeof(int));

            var pSubStatusCodeParameter = pSubStatusCode.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pSubStatusCode", pSubStatusCode) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pSubStatusCode", typeof(int));

            var pIsSecheduledParameter = pIsSecheduled.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pIsSecheduled", pIsSecheduled) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pIsSecheduled", typeof(bool));

            var pJobNameParameter = pJobName != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobName", pJobName) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobName", typeof(string));

            var pPreferedStartTimeParameter = pPreferedStartTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pPreferedStartTime", pPreferedStartTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pPreferedStartTime", typeof(System.DateTime));

            var pPreferedEndTimeParameter = pPreferedEndTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pPreferedEndTime", pPreferedEndTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pPreferedEndTime", typeof(System.DateTime));

            var pScheduledStartTimeParameter = pScheduledStartTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pScheduledStartTime", pScheduledStartTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pScheduledStartTime", typeof(System.DateTime));

            var pScheduledEndTimeParameter = pScheduledEndTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pScheduledEndTime", pScheduledEndTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pScheduledEndTime", typeof(System.DateTime));

            var pActialStartTimeParameter = pActialStartTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pActialStartTime", pActialStartTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pActialStartTime", typeof(System.DateTime));

            var pActualEndTimeParameter = pActualEndTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pActualEndTime", pActualEndTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pActualEndTime", typeof(System.DateTime));

            var pEstimatedDutationParameter = pEstimatedDutation.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pEstimatedDutation", pEstimatedDutation) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pEstimatedDutation", typeof(double));

            var pQuotedDurationParameter = pQuotedDuration.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pQuotedDuration", pQuotedDuration) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pQuotedDuration", typeof(double));

            var pActualDurationParameter = pActualDuration.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pActualDuration", pActualDuration) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pActualDuration", typeof(double));

            var pCostTypeParameter = pCostType.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pCostType", pCostType) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pCostType", typeof(short));

            var pQuotedCostParameter = pQuotedCost.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pQuotedCost", pQuotedCost) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pQuotedCost", typeof(double));

            var pActualCostParameter = pActualCost.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pActualCost", pActualCost) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pActualCost", typeof(double));

            var pJobFormParameter = pJobForm != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobForm", pJobForm) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobForm", typeof(string));

            var pJobFormGUIDParameter = pJobFormGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobFormGUID", pJobFormGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobFormGUID", typeof(System.Guid));

            var pSignOffRequiredParameter = pSignOffRequired.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pSignOffRequired", pSignOffRequired) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pSignOffRequired", typeof(short));

            var pSignoffNameParameter = pSignoffName != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pSignoffName", pSignoffName) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pSignoffName", typeof(string));

            var pPictureRequiredParameter = pPictureRequired.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pPictureRequired", pPictureRequired) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pPictureRequired", typeof(short));

            var pPictureDescriptionParameter = pPictureDescription != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pPictureDescription", pPictureDescription) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pPictureDescription", typeof(string));

            var pLocationSpecificParameter = pLocationSpecific.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLocationSpecific", pLocationSpecific) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLocationSpecific", typeof(bool));

            var pCreateDateParameter = pCreateDate.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pCreateDate", pCreateDate) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pCreateDate", typeof(System.DateTime));

            var pCreateByParameter = pCreateBy.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pCreateBy", pCreateBy) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pCreateBy", typeof(System.Guid));

            var pLastModifiedDateParameter = pLastModifiedDate.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLastModifiedDate", pLastModifiedDate) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLastModifiedDate", typeof(System.DateTime));

            var pLastModifiedByParameter = pLastModifiedBy.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLastModifiedBy", pLastModifiedBy) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLastModifiedBy", typeof(System.Guid));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_UpdateJob", pJobGUIDParameter, pJobReferenceNoParameter, pOrganizationGUIDParameter, pRegionGUIDParameter, pTerritoryGUIDParameter, pLocationTypeParameter, pCustomerGUIDParameter, pCustomerStopGUIDParameter, pServicePointGUIDParameter, pServiceAddressParameter, pLatitudeParameter, pLongitudeParameter, pAssignedUserGUIDParameter, pManagerUserGUIDParameter, pIsActiveParameter, pIsDeletedParameter, pIsUrgentParameter, pStatusCodeParameter, pSubStatusCodeParameter, pIsSecheduledParameter, pJobNameParameter, pPreferedStartTimeParameter, pPreferedEndTimeParameter, pScheduledStartTimeParameter, pScheduledEndTimeParameter, pActialStartTimeParameter, pActualEndTimeParameter, pEstimatedDutationParameter, pQuotedDurationParameter, pActualDurationParameter, pCostTypeParameter, pQuotedCostParameter, pActualCostParameter, pJobFormParameter, pJobFormGUIDParameter, pSignOffRequiredParameter, pSignoffNameParameter, pPictureRequiredParameter, pPictureDescriptionParameter, pLocationSpecificParameter, pCreateDateParameter, pCreateByParameter, pLastModifiedDateParameter, pLastModifiedByParameter, pErrorCode);
        }

        public virtual int p_UpdateJobStatus(Nullable<System.Guid> pJobProgressGUID, Nullable<System.Guid> pJobGUID, Nullable<int> pJobStatus, Nullable<int> pJobSubStatus, Nullable<System.DateTime> pStartTime, Nullable<System.DateTime> pEndTime, Nullable<double> pDuration, Nullable<double> pLatitude, Nullable<double> pLongitude, Nullable<System.DateTime> pLastModifiedDate, Nullable<System.Guid> pLastModifiedBy, string pStatusNote, System.Data.Entity.Core.Objects.ObjectParameter pErrorCode)
        {
            var pJobProgressGUIDParameter = pJobProgressGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobProgressGUID", pJobProgressGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobProgressGUID", typeof(System.Guid));

            var pJobGUIDParameter = pJobGUID.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobGUID", pJobGUID) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobGUID", typeof(System.Guid));

            var pJobStatusParameter = pJobStatus.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobStatus", pJobStatus) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobStatus", typeof(int));

            var pJobSubStatusParameter = pJobSubStatus.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobSubStatus", pJobSubStatus) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pJobSubStatus", typeof(int));

            var pStartTimeParameter = pStartTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pStartTime", pStartTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pStartTime", typeof(System.DateTime));

            var pEndTimeParameter = pEndTime.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pEndTime", pEndTime) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pEndTime", typeof(System.DateTime));

            var pDurationParameter = pDuration.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pDuration", pDuration) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pDuration", typeof(double));

            var pLatitudeParameter = pLatitude.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLatitude", pLatitude) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLatitude", typeof(double));

            var pLongitudeParameter = pLongitude.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLongitude", pLongitude) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLongitude", typeof(double));

            var pLastModifiedDateParameter = pLastModifiedDate.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLastModifiedDate", pLastModifiedDate) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLastModifiedDate", typeof(System.DateTime));

            var pLastModifiedByParameter = pLastModifiedBy.HasValue ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pLastModifiedBy", pLastModifiedBy) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pLastModifiedBy", typeof(System.Guid));

            var pStatusNoteParameter = pStatusNote != null ?
                new System.Data.Entity.Core.Objects.ObjectParameter("pStatusNote", pStatusNote) :
                new System.Data.Entity.Core.Objects.ObjectParameter("pStatusNote", typeof(string));

            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_UpdateJobStatus", pJobProgressGUIDParameter, pJobGUIDParameter, pJobStatusParameter, pJobSubStatusParameter, pStartTimeParameter, pEndTimeParameter, pDurationParameter, pLatitudeParameter, pLongitudeParameter, pLastModifiedDateParameter, pLastModifiedByParameter, pStatusNoteParameter, pErrorCode);
        }
    }
}
