//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkersInMotion.DataAccess.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkDaysOrganization
    {
        public WorkDaysOrganization()
        {
            this.WorkDaysUsers = new HashSet<WorkDaysUser>();
        }
    
        public System.Guid OrganizationWorkDaysGUID { get; set; }
        public System.Guid OrganizationGUID { get; set; }
        public string WorkDays { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public Nullable<System.Guid> LastModifiedBy { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual ICollection<WorkDaysUser> WorkDaysUsers { get; set; }
    }
}
